### ISSUE TITLE
Hexo 3 不兼容？

### ISSUE THREAD

**Issue by zekunyan** [coneycode/coney#11]
[error] TypeError: Cannot read property 'feed' of undefined
TypeError: Cannot read property 'feed' of undefined
    at module.exports (/Users/zorro/Projects/Github/Blog/node_modules/hexo-generator-feed/lib/generator.js:16:26)
    at /usr/local/lib/node_modules/hexo/lib/theme/index.js:113:7
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at async.each.called (/usr/local/lib/node_modules/hexo/lib/theme/index.js:112:7)
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:124:9)
    at Theme._generate (/usr/local/lib/node_modules/hexo/lib/theme/index.js:104:9)

**Comment by zekunyan** [comment]
环境：
hexo: 2.8.3
os: Darwin 14.1.0 darwin x64
http_parser: 1.0
node: 0.10.35
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1j

主题非常好用啊·~

**Comment by coneycode** [comment]
这个不是主题的问题吧？好像是hexo-generator-feed的问题吧?
或者你主题里的_config.yml写的不对？

**Comment by zekunyan** [comment]
是不是要Hexo 3.0以下？

**Comment by coneycode** [comment]
是的。。我没做过hexo 3.0的适配。。-_-!可是你的不是2.8吗？

**Comment by zekunyan** [comment]
升级了Hexo 3.0=。=，不好意思。

**Comment by coneycode** [comment]
3.0已经确认，可以使用。请题主自己试试。
